Add sample-scenario tutorial resources for APIM 4.1.0
wso2/samples-apim pull request #52
Opened 2022-04-11 09:15 UTC by chashikajw

## Purpose
$Subject

2022-04-12 05:28 UTC, chamilaadhi commented on apim-tutorial/backends/train-schedule/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.1.0"
don't hv to change these :D

2022-04-12 05:30 UTC, chamilaadhi requested changes

2022-04-12 05:30 UTC, chamilaadhi commented on apim-tutorial/dockerfiles/conf/apim/repository/conf/deployment.toml
> +auth_token = "2199f277-1ad4-4ca3-80c3-9d9a075a594a"
set it to false and remove the token

2022-04-12 05:33 UTC, chamilaadhi commented on apim-tutorial/dockerfiles/conf/apim/repository/conf/deployment.toml
>  [apim.analytics]
Add the deployment.toml file of the 4.1.0

2022-04-20 04:24 UTC, chashikajw commented on apim-tutorial/dockerfiles/conf/apim/repository/conf/deployment.toml
>  [apim.analytics]
Fixed in dce229a18566ef7fad25347d943a57a05adcc15c

2022-04-26 06:15 UTC, chamilaadhi approved these changes

2022-05-06 07:40 UTC, merged